version: "3"
services:
  react-app:
    image: frontend
    stdin_open: truecd
    ports: 
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: backend
    ports:
      - "5000:5000"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge